tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "shivammathur/php"
brew "apr-util"
brew "python@3.10"
brew "azure-cli"
brew "bash-completion"
brew "black", restart_service: true
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "coreutils"
brew "curl"
brew "freetds"
brew "git"
brew "harfbuzz"
brew "httpd", restart_service: true
brew "imagemagick"
brew "jq"
brew "nghttp2"
brew "node"
brew "json5"
brew "libicns"
brew "libpq"
brew "libxml2"
brew "logrotate", restart_service: true
brew "node@14"
brew "openssl@3"
brew "pandoc"
brew "tidy-html5"
brew "php@7.4", restart_service: true, link: true
brew "phpunit"
brew "ruby"
brew "switchaudio-osx"
brew "texlive"
brew "thefuck"
brew "yq"
brew "mongodb/brew/mongodb-community@4.4"
brew "shivammathur/php/php@8.0"
cask "ha-menu"
cask "mactex"
